version: '3.7'

services:
  nest:
    container_name: nest
    build:
      context: .
      target: ${APP_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - './docker/data/pg:/var/lib/postgresql/data'
networks:
  webnet:
